# Generated by Django 3.2.4 on 2021-08-16 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=50)),
                ('start_stop', models.CharField(max_length=50)),
                ('end_stop', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('start_lat', models.CharField(max_length=50)),
                ('start_long', models.CharField(max_length=50)),
                ('end_lat', models.CharField(max_length=50)),
                ('end_long', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
