# Generated by Django 3.2.4 on 2021-07-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_last_login'),
        ('users', '0014_alter_my_stations_id'),
    ]

    operations = [
    ]
