# Generated by Django 3.2.4 on 2021-08-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20210720_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nametoid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
